### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by jeboehm**
😉

### CODE REVIEW

**Comment by shyim** [comment]
ty 😂

**Comment by jeboehm** [comment]
You're very welcome!

**Comment by shyim** [comment]
was the wrong file editied the correct one 😂  
https://github.com/shyim/shyim/commit/bb4d9be90a0c1a22eb7c5d40c1f03c418d4e671a

**Comment by jeboehm** [comment]
Einmal mit Profis...

**Pull request merged**
